/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IntakeBusinessIdRouteImport } from './routes/intake.$businessId'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard/settings'
import { Route as AuthenticatedDashboardReviewsRouteImport } from './routes/_authenticated/dashboard/reviews'
import { Route as AuthenticatedDashboardMissedCallsRouteImport } from './routes/_authenticated/dashboard/missed-calls'
import { Route as AuthenticatedDashboardIntakesRouteImport } from './routes/_authenticated/dashboard/intakes'
import { Route as AuthenticatedDashboardDeadLeadsRouteImport } from './routes/_authenticated/dashboard/dead-leads'
import { Route as AuthenticatedDashboardContactsRouteImport } from './routes/_authenticated/dashboard/contacts'
import { Route as AuthenticatedDashboardQuotesIndexRouteImport } from './routes/_authenticated/dashboard/quotes.index'
import { Route as ApiPublicTwilioVoiceRouteImport } from './routes/api/public/twilio/voice'
import { Route as ApiPublicTwilioSmsRouteImport } from './routes/api/public/twilio/sms'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as AuthenticatedDashboardQuotesNewRouteImport } from './routes/_authenticated/dashboard/quotes.new'
import { Route as AuthenticatedDashboardAdminNumbersRouteImport } from './routes/_authenticated/dashboard/admin/numbers'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeBusinessIdRoute = IntakeBusinessIdRouteImport.update({
  id: '/intake/$businessId',
  path: '/intake/$businessId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/dashboard/settings',
    path: '/dashboard/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardReviewsRoute =
  AuthenticatedDashboardReviewsRouteImport.update({
    id: '/dashboard/reviews',
    path: '/dashboard/reviews',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardMissedCallsRoute =
  AuthenticatedDashboardMissedCallsRouteImport.update({
    id: '/dashboard/missed-calls',
    path: '/dashboard/missed-calls',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIntakesRoute =
  AuthenticatedDashboardIntakesRouteImport.update({
    id: '/dashboard/intakes',
    path: '/dashboard/intakes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardDeadLeadsRoute =
  AuthenticatedDashboardDeadLeadsRouteImport.update({
    id: '/dashboard/dead-leads',
    path: '/dashboard/dead-leads',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardContactsRoute =
  AuthenticatedDashboardContactsRouteImport.update({
    id: '/dashboard/contacts',
    path: '/dashboard/contacts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardQuotesIndexRoute =
  AuthenticatedDashboardQuotesIndexRouteImport.update({
    id: '/dashboard/quotes/',
    path: '/dashboard/quotes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicTwilioVoiceRoute = ApiPublicTwilioVoiceRouteImport.update({
  id: '/api/public/twilio/voice',
  path: '/api/public/twilio/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioSmsRoute = ApiPublicTwilioSmsRouteImport.update({
  id: '/api/public/twilio/sms',
  path: '/api/public/twilio/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardQuotesNewRoute =
  AuthenticatedDashboardQuotesNewRouteImport.update({
    id: '/dashboard/quotes/new',
    path: '/dashboard/quotes/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAdminNumbersRoute =
  AuthenticatedDashboardAdminNumbersRouteImport.update({
    id: '/dashboard/admin/numbers',
    path: '/dashboard/admin/numbers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/intake/$businessId': typeof IntakeBusinessIdRoute
  '/dashboard/contacts': typeof AuthenticatedDashboardContactsRoute
  '/dashboard/dead-leads': typeof AuthenticatedDashboardDeadLeadsRoute
  '/dashboard/intakes': typeof AuthenticatedDashboardIntakesRoute
  '/dashboard/missed-calls': typeof AuthenticatedDashboardMissedCallsRoute
  '/dashboard/reviews': typeof AuthenticatedDashboardReviewsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/admin/numbers': typeof AuthenticatedDashboardAdminNumbersRoute
  '/dashboard/quotes/new': typeof AuthenticatedDashboardQuotesNewRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/twilio/sms': typeof ApiPublicTwilioSmsRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
  '/dashboard/quotes/': typeof AuthenticatedDashboardQuotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/intake/$businessId': typeof IntakeBusinessIdRoute
  '/dashboard/contacts': typeof AuthenticatedDashboardContactsRoute
  '/dashboard/dead-leads': typeof AuthenticatedDashboardDeadLeadsRoute
  '/dashboard/intakes': typeof AuthenticatedDashboardIntakesRoute
  '/dashboard/missed-calls': typeof AuthenticatedDashboardMissedCallsRoute
  '/dashboard/reviews': typeof AuthenticatedDashboardReviewsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/admin/numbers': typeof AuthenticatedDashboardAdminNumbersRoute
  '/dashboard/quotes/new': typeof AuthenticatedDashboardQuotesNewRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/twilio/sms': typeof ApiPublicTwilioSmsRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
  '/dashboard/quotes': typeof AuthenticatedDashboardQuotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/intake/$businessId': typeof IntakeBusinessIdRoute
  '/_authenticated/dashboard/contacts': typeof AuthenticatedDashboardContactsRoute
  '/_authenticated/dashboard/dead-leads': typeof AuthenticatedDashboardDeadLeadsRoute
  '/_authenticated/dashboard/intakes': typeof AuthenticatedDashboardIntakesRoute
  '/_authenticated/dashboard/missed-calls': typeof AuthenticatedDashboardMissedCallsRoute
  '/_authenticated/dashboard/reviews': typeof AuthenticatedDashboardReviewsRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/admin/numbers': typeof AuthenticatedDashboardAdminNumbersRoute
  '/_authenticated/dashboard/quotes/new': typeof AuthenticatedDashboardQuotesNewRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/twilio/sms': typeof ApiPublicTwilioSmsRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
  '/_authenticated/dashboard/quotes/': typeof AuthenticatedDashboardQuotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/intake/$businessId'
    | '/dashboard/contacts'
    | '/dashboard/dead-leads'
    | '/dashboard/intakes'
    | '/dashboard/missed-calls'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/admin/numbers'
    | '/dashboard/quotes/new'
    | '/api/public/payments/webhook'
    | '/api/public/twilio/sms'
    | '/api/public/twilio/voice'
    | '/dashboard/quotes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/intake/$businessId'
    | '/dashboard/contacts'
    | '/dashboard/dead-leads'
    | '/dashboard/intakes'
    | '/dashboard/missed-calls'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/admin/numbers'
    | '/dashboard/quotes/new'
    | '/api/public/payments/webhook'
    | '/api/public/twilio/sms'
    | '/api/public/twilio/voice'
    | '/dashboard/quotes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/onboarding'
    | '/intake/$businessId'
    | '/_authenticated/dashboard/contacts'
    | '/_authenticated/dashboard/dead-leads'
    | '/_authenticated/dashboard/intakes'
    | '/_authenticated/dashboard/missed-calls'
    | '/_authenticated/dashboard/reviews'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/admin/numbers'
    | '/_authenticated/dashboard/quotes/new'
    | '/api/public/payments/webhook'
    | '/api/public/twilio/sms'
    | '/api/public/twilio/voice'
    | '/_authenticated/dashboard/quotes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  IntakeBusinessIdRoute: typeof IntakeBusinessIdRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicTwilioSmsRoute: typeof ApiPublicTwilioSmsRoute
  ApiPublicTwilioVoiceRoute: typeof ApiPublicTwilioVoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake/$businessId': {
      id: '/intake/$businessId'
      path: '/intake/$businessId'
      fullPath: '/intake/$businessId'
      preLoaderRoute: typeof IntakeBusinessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/reviews': {
      id: '/_authenticated/dashboard/reviews'
      path: '/dashboard/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof AuthenticatedDashboardReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/missed-calls': {
      id: '/_authenticated/dashboard/missed-calls'
      path: '/dashboard/missed-calls'
      fullPath: '/dashboard/missed-calls'
      preLoaderRoute: typeof AuthenticatedDashboardMissedCallsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/intakes': {
      id: '/_authenticated/dashboard/intakes'
      path: '/dashboard/intakes'
      fullPath: '/dashboard/intakes'
      preLoaderRoute: typeof AuthenticatedDashboardIntakesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/dead-leads': {
      id: '/_authenticated/dashboard/dead-leads'
      path: '/dashboard/dead-leads'
      fullPath: '/dashboard/dead-leads'
      preLoaderRoute: typeof AuthenticatedDashboardDeadLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/contacts': {
      id: '/_authenticated/dashboard/contacts'
      path: '/dashboard/contacts'
      fullPath: '/dashboard/contacts'
      preLoaderRoute: typeof AuthenticatedDashboardContactsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/quotes/': {
      id: '/_authenticated/dashboard/quotes/'
      path: '/dashboard/quotes'
      fullPath: '/dashboard/quotes/'
      preLoaderRoute: typeof AuthenticatedDashboardQuotesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/twilio/voice': {
      id: '/api/public/twilio/voice'
      path: '/api/public/twilio/voice'
      fullPath: '/api/public/twilio/voice'
      preLoaderRoute: typeof ApiPublicTwilioVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/sms': {
      id: '/api/public/twilio/sms'
      path: '/api/public/twilio/sms'
      fullPath: '/api/public/twilio/sms'
      preLoaderRoute: typeof ApiPublicTwilioSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/quotes/new': {
      id: '/_authenticated/dashboard/quotes/new'
      path: '/dashboard/quotes/new'
      fullPath: '/dashboard/quotes/new'
      preLoaderRoute: typeof AuthenticatedDashboardQuotesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/admin/numbers': {
      id: '/_authenticated/dashboard/admin/numbers'
      path: '/dashboard/admin/numbers'
      fullPath: '/dashboard/admin/numbers'
      preLoaderRoute: typeof AuthenticatedDashboardAdminNumbersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedDashboardContactsRoute: typeof AuthenticatedDashboardContactsRoute
  AuthenticatedDashboardDeadLeadsRoute: typeof AuthenticatedDashboardDeadLeadsRoute
  AuthenticatedDashboardIntakesRoute: typeof AuthenticatedDashboardIntakesRoute
  AuthenticatedDashboardMissedCallsRoute: typeof AuthenticatedDashboardMissedCallsRoute
  AuthenticatedDashboardReviewsRoute: typeof AuthenticatedDashboardReviewsRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardAdminNumbersRoute: typeof AuthenticatedDashboardAdminNumbersRoute
  AuthenticatedDashboardQuotesNewRoute: typeof AuthenticatedDashboardQuotesNewRoute
  AuthenticatedDashboardQuotesIndexRoute: typeof AuthenticatedDashboardQuotesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedDashboardContactsRoute: AuthenticatedDashboardContactsRoute,
  AuthenticatedDashboardDeadLeadsRoute: AuthenticatedDashboardDeadLeadsRoute,
  AuthenticatedDashboardIntakesRoute: AuthenticatedDashboardIntakesRoute,
  AuthenticatedDashboardMissedCallsRoute:
    AuthenticatedDashboardMissedCallsRoute,
  AuthenticatedDashboardReviewsRoute: AuthenticatedDashboardReviewsRoute,
  AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDashboardAdminNumbersRoute:
    AuthenticatedDashboardAdminNumbersRoute,
  AuthenticatedDashboardQuotesNewRoute: AuthenticatedDashboardQuotesNewRoute,
  AuthenticatedDashboardQuotesIndexRoute:
    AuthenticatedDashboardQuotesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  IntakeBusinessIdRoute: IntakeBusinessIdRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicTwilioSmsRoute: ApiPublicTwilioSmsRoute,
  ApiPublicTwilioVoiceRoute: ApiPublicTwilioVoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
