/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard/settings'
import { Route as AuthenticatedDashboardReviewsRouteImport } from './routes/_authenticated/dashboard/reviews'
import { Route as AuthenticatedDashboardMissedCallsRouteImport } from './routes/_authenticated/dashboard/missed-calls'
import { Route as AuthenticatedDashboardDeadLeadsRouteImport } from './routes/_authenticated/dashboard/dead-leads'
import { Route as ApiPublicTwilioVoiceRouteImport } from './routes/api/public/twilio/voice'
import { Route as ApiPublicTwilioSmsRouteImport } from './routes/api/public/twilio/sms'
import { Route as AuthenticatedDashboardAdminNumbersRouteImport } from './routes/_authenticated/dashboard/admin/numbers'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/dashboard/settings',
    path: '/dashboard/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardReviewsRoute =
  AuthenticatedDashboardReviewsRouteImport.update({
    id: '/dashboard/reviews',
    path: '/dashboard/reviews',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardMissedCallsRoute =
  AuthenticatedDashboardMissedCallsRouteImport.update({
    id: '/dashboard/missed-calls',
    path: '/dashboard/missed-calls',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardDeadLeadsRoute =
  AuthenticatedDashboardDeadLeadsRouteImport.update({
    id: '/dashboard/dead-leads',
    path: '/dashboard/dead-leads',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicTwilioVoiceRoute = ApiPublicTwilioVoiceRouteImport.update({
  id: '/api/public/twilio/voice',
  path: '/api/public/twilio/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTwilioSmsRoute = ApiPublicTwilioSmsRouteImport.update({
  id: '/api/public/twilio/sms',
  path: '/api/public/twilio/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardAdminNumbersRoute =
  AuthenticatedDashboardAdminNumbersRouteImport.update({
    id: '/dashboard/admin/numbers',
    path: '/dashboard/admin/numbers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/dashboard/dead-leads': typeof AuthenticatedDashboardDeadLeadsRoute
  '/dashboard/missed-calls': typeof AuthenticatedDashboardMissedCallsRoute
  '/dashboard/reviews': typeof AuthenticatedDashboardReviewsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/admin/numbers': typeof AuthenticatedDashboardAdminNumbersRoute
  '/api/public/twilio/sms': typeof ApiPublicTwilioSmsRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/dashboard/dead-leads': typeof AuthenticatedDashboardDeadLeadsRoute
  '/dashboard/missed-calls': typeof AuthenticatedDashboardMissedCallsRoute
  '/dashboard/reviews': typeof AuthenticatedDashboardReviewsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/admin/numbers': typeof AuthenticatedDashboardAdminNumbersRoute
  '/api/public/twilio/sms': typeof ApiPublicTwilioSmsRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/dashboard/dead-leads': typeof AuthenticatedDashboardDeadLeadsRoute
  '/_authenticated/dashboard/missed-calls': typeof AuthenticatedDashboardMissedCallsRoute
  '/_authenticated/dashboard/reviews': typeof AuthenticatedDashboardReviewsRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/admin/numbers': typeof AuthenticatedDashboardAdminNumbersRoute
  '/api/public/twilio/sms': typeof ApiPublicTwilioSmsRoute
  '/api/public/twilio/voice': typeof ApiPublicTwilioVoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/dashboard/dead-leads'
    | '/dashboard/missed-calls'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/admin/numbers'
    | '/api/public/twilio/sms'
    | '/api/public/twilio/voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/dashboard/dead-leads'
    | '/dashboard/missed-calls'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/admin/numbers'
    | '/api/public/twilio/sms'
    | '/api/public/twilio/voice'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/onboarding'
    | '/_authenticated/dashboard/dead-leads'
    | '/_authenticated/dashboard/missed-calls'
    | '/_authenticated/dashboard/reviews'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/admin/numbers'
    | '/api/public/twilio/sms'
    | '/api/public/twilio/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicTwilioSmsRoute: typeof ApiPublicTwilioSmsRoute
  ApiPublicTwilioVoiceRoute: typeof ApiPublicTwilioVoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/reviews': {
      id: '/_authenticated/dashboard/reviews'
      path: '/dashboard/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof AuthenticatedDashboardReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/missed-calls': {
      id: '/_authenticated/dashboard/missed-calls'
      path: '/dashboard/missed-calls'
      fullPath: '/dashboard/missed-calls'
      preLoaderRoute: typeof AuthenticatedDashboardMissedCallsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/dead-leads': {
      id: '/_authenticated/dashboard/dead-leads'
      path: '/dashboard/dead-leads'
      fullPath: '/dashboard/dead-leads'
      preLoaderRoute: typeof AuthenticatedDashboardDeadLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/twilio/voice': {
      id: '/api/public/twilio/voice'
      path: '/api/public/twilio/voice'
      fullPath: '/api/public/twilio/voice'
      preLoaderRoute: typeof ApiPublicTwilioVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/twilio/sms': {
      id: '/api/public/twilio/sms'
      path: '/api/public/twilio/sms'
      fullPath: '/api/public/twilio/sms'
      preLoaderRoute: typeof ApiPublicTwilioSmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/admin/numbers': {
      id: '/_authenticated/dashboard/admin/numbers'
      path: '/dashboard/admin/numbers'
      fullPath: '/dashboard/admin/numbers'
      preLoaderRoute: typeof AuthenticatedDashboardAdminNumbersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedDashboardDeadLeadsRoute: typeof AuthenticatedDashboardDeadLeadsRoute
  AuthenticatedDashboardMissedCallsRoute: typeof AuthenticatedDashboardMissedCallsRoute
  AuthenticatedDashboardReviewsRoute: typeof AuthenticatedDashboardReviewsRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardAdminNumbersRoute: typeof AuthenticatedDashboardAdminNumbersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedDashboardDeadLeadsRoute: AuthenticatedDashboardDeadLeadsRoute,
  AuthenticatedDashboardMissedCallsRoute:
    AuthenticatedDashboardMissedCallsRoute,
  AuthenticatedDashboardReviewsRoute: AuthenticatedDashboardReviewsRoute,
  AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDashboardAdminNumbersRoute:
    AuthenticatedDashboardAdminNumbersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicTwilioSmsRoute: ApiPublicTwilioSmsRoute,
  ApiPublicTwilioVoiceRoute: ApiPublicTwilioVoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
